
# Stage 1: Build environment
FROM python:3.9-slim AS builder

WORKDIR /app

COPY . .

# Stage 2: Runtime environment
FROM python:3.9-slim

WORKDIR /app

COPY --from=builder /app .

CMD ["python", "tic_tac_toe.py"]
